### PR TITLE
Test multiplication

### PR DESCRIPTION
**Pull request by alvinypyim**
# Testing

```
$ node_modules/.bin/karma start
```

### CODE REVIEW

**Comment by AlessandroBerardi** [comment]
:+1:

**Comment by mnoack** [comment]
:+1:

**Comment by mnoack** [comment]
A great follow up PR @alvinypyim would be to get quicktravel/spec/javascripts/libs/money_spec.js.coffee and put that in here, which should be easy, and eventually have QT use that library (a bit more work since QT doesn't use webpack yet - but I had that in a branch)

**Comment by jackmcpickle** [comment]
@alvinypyim a couple of comments. 

first the dist file which is used in package.json > main value needs to be generated and then published.

**Comment by jackmcpickle** [comment]
also any command in the node_packages/.bin folder can just be run with `npm run`

**Comment by jackmcpickle** [comment]
also probably dont need to use phantomjs just to run a few unit tests. As this is only needed if we need a DOM. Try something like, https://github.com/mjackson/expect

**Pull request merged**
